# Please edit the object below. Lines beginning with a '#' will be ignored,
# and an empty file will abort the edit. If an error occurs while saving this file will be
# reopened with the relevant failures.
#
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
  labels:
    name: test-bigip-controller-1
  name: test-bigip-controller-1
  namespace: kube-system
spec:
  selector:
    matchLabels:
      app: test-bigip-controller-1
  template:
    metadata:
      labels:
        app: test-bigip-controller-1
    spec:
      containers:
      - args:
        - --bigip-partition
        - controller1
        - --bigip-url
        - 10.x.x.x
        - --bigip-username
        - <username>
        - --bigip-password
        - <password>
        - --as3-validation=true
        - --insecure
        - --log-as3-response=true
        - --share-nodes=true
        - --custom-resource-mode=true
        - --disable-teems=true
        - --pool-member-type
        - nodeport
        command:
        - /app/bin/k8s-bigip-ctlr
        image: f5networks/k8s-bigip-ctlr:latest
        imagePullPolicy: IfNotPresent
        name: test-bigip-controller-1
      serviceAccount: bigip-ctlr
      serviceAccountName: bigip-ctlr

