apiVersion: "cis.f5.com/v1"
kind: VirtualServer
metadata:
  name: cafe-virtual-server
  labels:
    f5cr: "true"
spec:
  # This is an insecure virtual, Please use TLSProfile to secure the virtual
  # check out tls examples to understand more.
  host: cafe.example.com
  virtualServerName: "cafe-virtual-server"
  virtualServerAddress: "172.16.4.214" #vip(external IP for virtual) on bigip1
  additionalVirtualServerAddresses:
  - "172.16.8.172" #vip(external IP for virtual) on bigip2
  pools:
  - path: /coffee
    service: svc-1
    servicePort: 80

