# Please edit the object below. Lines beginning with a '#' will be ignored,
# and an empty file will abort the edit. If an error occurs while saving this file will be
# reopened with the relevant failures.
#
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
  labels:
    name: svc-1
  name: svc-1
spec:
  selector:
    matchLabels:
      app: svc-1
  template:
    metadata:
      annotations:
      labels:
        app: svc-1
    spec:
      containers:
      - env:
        - name: service_name
          value: svc-1
        image: f5networksdevel/test-nginx:latest
        imagePullPolicy: IfNotPresent
        name: svc-1
        ports:
        - containerPort: 80
          protocol: TCP

